const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const core = require('../assets/tempo-core.js');
assert.equal(core.calibrate(18,16),67.5);
assert.equal(core.calibrate(9,16,'cycles'),67.5);
assert.equal(core.interval(67.5).toFixed(2),'0.89');
assert.equal(core.interval(66,'cycles'),core.interval(66)*2);
assert.equal(core.fromInterval(core.interval(70)),70);
for(const value of [0,-1,NaN,Infinity,241])assert.throws(()=>core.interval(value));
for(const args of [[0,16],[18,0],[18,NaN],[18,16,'bad']])assert.throws(()=>core.calibrate(...args));
const profile={version:1,targets:{hundred:67.5},observations:{hundred:{count:18,seconds:16,unit:'arms',method:'estimate',pool:25,date:new Date().toISOString(),time25:16,effort:null}},mode:'arms'};
core.validateProfile(profile);
assert.throws(()=>core.validateProfile({...profile,targets:{easy:-1}}));
const data = new Map(); let fail=false;
const localStorage={getItem:k=>data.get(k)??null,setItem:(k,v)=>{if(fail)throw Error('quota');data.set(k,v);}};
const revision='test-plan';
data.set(`lane50:${revision}:records`,JSON.stringify({version:1,records:{'race:50':{result:'35.4'}}}));
function load(rev){const context={window:{addEventListener(){}},document:{dispatchEvent(){}},Event:class{},localStorage,PREPARATION:{revision:rev,days:[]}};vm.runInNewContext(fs.readFileSync('assets/storage.js','utf8'),context);return context.window.LaneStorage;}
const store=load(revision);
assert.equal(store.get('race:50').result,'35.4');
assert(store.save('tempo:profile',profile));
assert.equal(load('new-plan').get('tempo:profile').targets.hundred,67.5);
assert.equal(load(revision).get('race:50').result,'35.4');
fail=true;assert.equal(store.save('tempo:profile',{...profile,mode:'cycles'}),false);assert(store.unsaved);
assert.equal(store.records()['tempo:profile'].mode,'cycles');
const before=data.get('lane50:portable-v1');
assert.throws(()=>store.restore({'race:50':{result:'30'}}));assert.equal(data.get('lane50:portable-v1'),before);
fail=false;assert(store.retry());assert.equal(load(revision).get('tempo:profile').mode,'cycles');
store.restore({'race:50':{result:'32'}});assert.equal(store.get('race:50').result,'32');assert.equal(store.get('tempo:profile').mode,'cycles');
console.log('PASS tempo conversions, partial profiles, migration, cross-plan persistence, failed writes, retry and atomic restore');
