/* Validate the breaststroke plan and generate the browser data bundle. */
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const plan = JSON.parse(fs.readFileSync(path.join(root, 'data/competition-plan.json'), 'utf8'));
const source = fs.readFileSync(path.join(root, 'BREASTSTROKE-PLAN.md'), 'utf8');
const heading = /^(?:##|###) (?:Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|Monday), \d{1,2} \w+ — .+$/gm;
const matches = [...source.matchAll(heading)];
const sections = matches.map((match, index) => source.slice(match.index, matches[index + 1]?.index ?? source.length).trim());
const expectedTotals = [850, 950, 710, 600, 0, 400, 600, 500, 300, 400, 350, 0, 250, 400];
assert.equal(plan.days.length, 14);
assert.equal(sections.length, 14, 'The source must contain all 14 dated breaststroke sessions');
const output = structuredClone(plan);
output.days.forEach((day, index) => {
  const date = new Date(Date.UTC(2026, 8, 29 + index)).toISOString().slice(0, 10);
  assert.equal(day.id, date);
  assert.equal(day.date, date);
  assert.equal(day.total, expectedTotals[index], `Incorrect daily total: ${date}`);
  assert.equal(day.sets.filter(set => !set.optional).reduce((sum, set) => sum + set.metres, 0), day.total);
  assert.equal(new Set(day.sets.map(set => set.id)).size, day.sets.length);
  day.sets.forEach(set => {
    assert.ok(set.prescription && set.name);
    assert.ok(Number.isFinite(set.metres) && set.metres > 0);
    assert.ok(Array.isArray(set.timers));
    set.timers.forEach(timer => assert.ok(timer.seconds.length && timer.seconds.every(seconds => seconds > 0)));
  });
  output.days[index].source = sections[index];
});
assert.equal(plan.days.slice(0, 7).reduce((sum, day) => sum + day.total, 0), 4110);
assert.equal(plan.days.slice(7, 13).reduce((sum, day) => sum + day.total, 0), 1800);
assert.deepEqual(plan.days.filter(day => day.kind === 'Rest').map(day => day.date), ['2026-10-03', '2026-10-10']);
assert.deepEqual(plan.days.filter(day => day.kind === 'Race').map(day => [day.date, day.event]), [['2026-10-12', 50]]);
fs.writeFileSync(path.join(root, 'assets/data.js'), '/* Generated by scripts/import-plan.cjs; edit data/competition-plan.json. */\nconst PREPARATION = ' + JSON.stringify(output, null, 2) + ';\n');
console.log('Validated 14 breaststroke dates, source sections, totals, and rest durations. Generated assets/data.js.');
