/* Validate the supplied final taper schedule and generate its browser bundle. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const plan=JSON.parse(fs.readFileSync(path.join(root,'data/competition-plan.json'),'utf8'));
const source=fs.readFileSync(path.join(root,'SWIMMING-PLAN.md'),'utf8');
const headers=[...source.matchAll(/^#{1,2} Oct (\d+) — (.+)$/gm)];
assert.equal(plan.days.length,10);assert.equal(headers.length,10);
assert.equal(plan.startDate,'2026-10-04');assert.equal(plan.endDate,'2026-10-13');
for(const [i,day] of plan.days.entries()){
  const date=`2026-10-${String(i+4).padStart(2,'0')}`;
  assert.equal(day.id,date);assert.equal(day.date,date);
  const end=headers[i+1]?.index??source.indexOf('## Your daily intensity pattern');
  assert.equal(day.source,source.slice(headers[i].index,end).trim(),`Source excerpt differs for ${date}`);
  assert.deepEqual(Object.keys(day.phases),['before','am','evening']);
  assert.deepEqual(day.sets,day.phases.am.sets);
  for(const [phase,p] of Object.entries(day.phases)){
    assert(['planned','optional','off','unspecified'].includes(p.status));
    assert.equal(new Set(p.sets.map(s=>s.id)).size,p.sets.length);
    if(p.status==='off'||p.status==='unspecified')assert.equal(p.sets.length,0);
    assert.equal(p.knownMetres,p.sets.reduce((sum,s)=>sum+(s.metres??0),0));
    p.sets.forEach((s,j)=>{
      assert.equal(s.id,`${phase}-${j+1}`);assert(s.group&&s.name&&s.prescription);
      assert(s.metres===null||(Number.isFinite(s.metres)&&s.metres>0));
      s.timers.forEach(t=>assert(t.label&&t.seconds.length&&t.seconds.every(n=>Number.isFinite(n)&&n>0&&n<=3600)));
      if(s.rest==='Full recovery'||!s.rest)assert.equal(s.timers.length,0,'Do not invent a timer for full/unspecified recovery.');
    });
  }
}
assert.equal(plan.days[6].kind,'Rest');assert.equal(plan.days[6].sets.length,0);
assert.equal(plan.days[8].event,50);assert.equal(plan.days[9].event,100);
assert.equal(plan.days[2].phases.am.knownMetres,1300);
const broken=plan.days[4].sets.filter(s=>s.group==='Broken 50s');
assert.equal(broken.length,2);assert.deepEqual(broken[0].timers[1].seconds,[240,270,300]);
fs.writeFileSync(path.join(root,'assets/data.js'),'/* Generated by scripts/import-plan.cjs; edit data/competition-plan.json. */\nconst PREPARATION = '+JSON.stringify(plan,null,2)+';\n');
console.log('Validated 10 dates, exact source excerpts, AM/activation/mobility phases, rest semantics and distance estimates. Generated assets/data.js.');
