/* Validate the approved structured plan and generate the browser data bundle. */
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const plan = JSON.parse(fs.readFileSync(path.join(root, 'data/competition-plan.json'), 'utf8'));
const source = fs.readFileSync(path.join(root, 'SWIMMING-PLAN.md'), 'utf8');
const sections = source.split(/^# (?=(?:Sat|Sun|Mon|Tue|Wed|Thu|Fri|MON|TUE) )/m).slice(1);
const expected = [0,850,1000,900,700,850,950,0,700,700,700,500,550,400,0,300,500,550];
assert.equal(plan.days.length, 18);
assert.equal(sections.length, 18, 'The source must be the September 26–October 13 plan');
plan.days.forEach((day, i) => {
  const date = new Date(Date.UTC(2026, 8, 26 + i)).toISOString().slice(0,10);
  assert.equal(day.id, date);
  assert.equal(day.date, date);
  assert.equal(day.source, '# ' + sections[i].trim(), `Source excerpt changed: ${date}`);
  assert.equal(day.total, expected[i], `Incorrect daily total: ${date}`);
  assert.equal(day.sets.filter(s => !s.optional).reduce((n,s) => n+s.metres,0), day.total);
  assert.equal(new Set(day.sets.map(s => s.id)).size, day.sets.length);
  day.sets.forEach(s => {
    assert.ok(s.prescription && s.name);
    assert.ok(Number.isFinite(s.metres) && s.metres > 0);
    s.timers.forEach(t => assert.ok(t.seconds.length && t.seconds.every(n => n > 0)));
  });
});
assert.equal(plan.days.slice(9,16).reduce((n,d) => n+d.total,0),3150);
fs.writeFileSync(path.join(root, 'assets/data.js'), '/* Generated by scripts/import-plan.cjs; edit data/competition-plan.json. */\nconst PREPARATION = ' + JSON.stringify(plan,null,2) + ';\n');
console.log('Validated 18 dates, source excerpts, set totals, and rest durations. Generated assets/data.js.');
